# Generated by Django 6.0.8 on 2026-08-31 19:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('slug', models.SlugField(unique=True, verbose_name='identificador')),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='preço')),
                ('billing_period', models.CharField(choices=[('monthly', 'Mensal'), ('yearly', 'Anual')], default='monthly', max_length=10, verbose_name='periodicidade')),
                ('limits', models.JSONField(blank=True, default=dict, help_text='Ex.: {"active_diets": 1, "auto_reminders": false, "ai_enabled": false}. Vazio = sem limite.', verbose_name='limites')),
                ('is_active', models.BooleanField(default=True, verbose_name='disponível para assinatura')),
            ],
            options={
                'verbose_name': 'plano',
                'verbose_name_plural': 'planos',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('trial', 'Teste'), ('active', 'Ativa'), ('cancelled', 'Cancelada'), ('past_due', 'Inadimplente')], default='trial', max_length=10, verbose_name='situação')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='início')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('gateway_customer_id', models.CharField(blank=True, max_length=120, verbose_name='id do cliente no gateway')),
                ('gateway_subscription_id', models.CharField(blank=True, max_length=120, verbose_name='id da assinatura no gateway')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan', verbose_name='plano')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'assinatura',
                'verbose_name_plural': 'assinaturas',
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['trial', 'active', 'past_due'])), fields=('user',), name='uma_assinatura_corrente_por_usuario')],
            },
        ),
    ]
