# Generated by Django 6.0.8 on 2026-09-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('event_id', models.CharField(max_length=160, unique=True, verbose_name='id do evento')),
                ('topic', models.CharField(max_length=60, verbose_name='tópico')),
                ('status', models.CharField(blank=True, max_length=60, verbose_name='situação processada')),
            ],
            options={
                'verbose_name': 'evento de webhook',
                'verbose_name_plural': 'eventos de webhook',
                'ordering': ['-created_at'],
            },
        ),
    ]
