"""
The reminder inbox that consolidates triggers from every other area.

A ``Reminder`` either points back at the record that generated it (a medication dose, a
scheduled exam, a return date, a planned meal) through the generic ``source`` field, or has
none at all — a reminder the person typed by hand. Derived reminders are regenerated by
``lembretes.services.sync_reminders`` on every visit to the central and by the
``send_due_reminders`` management command; manual ones are never touched by that sync.
"""

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.urls import reverse
from django.utils import timezone

from core.models import OwnedModel


class Reminder(OwnedModel):
    class Category(models.TextChoices):
        MEDICATION = 'remedio', 'Remédio'
        EXAM = 'exame', 'Exame'
        RETURN = 'retorno', 'Retorno médico'
        # Marcar algo que ainda não tem data: o único grupo que sai por e-mail (D-044).
        SCHEDULING = 'agendar', 'Agendamento'
        TRAINING = 'treino', 'Treino'
        NUTRITION = 'nutricao', 'Nutrição'
        OTHER = 'outro', 'Outro'

    class Status(models.TextChoices):
        PENDING = 'pendente', 'Pendente'
        SENT = 'enviado', 'Enviado'
        DONE = 'concluido', 'Concluído'
        CANCELLED = 'cancelado', 'Cancelado'

    category = models.CharField('categoria', max_length=10, choices=Category.choices)
    title = models.CharField('título', max_length=180)
    description = models.TextField('descrição', blank=True)
    remind_at = models.DateTimeField('lembrar em')
    is_recurring = models.BooleanField('recorrente', default=False)
    recurrence_rule = models.CharField(
        'recorrência', max_length=80, blank=True,
        help_text='Texto livre para a pessoa lembrar o padrão. Ex.: "todo dia às 08:00".',
    )
    status = models.CharField('situação', max_length=10, choices=Status.choices, default=Status.PENDING)
    sent_at = models.DateTimeField('enviado em', null=True, blank=True)

    # Aponta pro registro que originou o lembrete (Medication, Exam, Appointment, Meal).
    # Em branco quando a pessoa cria o lembrete na mão — sync_reminders nunca mexe nesses.
    content_type = models.ForeignKey(
        ContentType, on_delete=models.CASCADE, null=True, blank=True, verbose_name='tipo de origem',
    )
    object_id = models.PositiveIntegerField('id de origem', null=True, blank=True)
    source = GenericForeignKey('content_type', 'object_id')

    class Meta:
        verbose_name = 'lembrete'
        verbose_name_plural = 'lembretes'
        ordering = ['remind_at']
        indexes = [
            models.Index(fields=['user', 'status', 'remind_at']),
            models.Index(fields=['content_type', 'object_id']),
        ]

    def __str__(self):
        return f'{self.title} · {self.remind_at:%d/%m/%Y %H:%M}'

    def get_absolute_url(self):
        return reverse('lembretes:index')

    @property
    def is_due(self):
        return self.status == self.Status.PENDING and self.remind_at <= timezone.now()

    def mark_done(self):
        self.status = self.Status.DONE
        self.save(update_fields=['status', 'updated_at'])

    def mark_cancelled(self):
        self.status = self.Status.CANCELLED
        self.save(update_fields=['status', 'updated_at'])


class ChannelPreference(OwnedModel):
    """
    Which channels a category of reminder is allowed to leave through, per person.

    Before this, ``Profile.notification_channel`` was a single value for everything: choosing
    WhatsApp moved *all* notices at once, which is why the safe answer was to notify almost
    nothing (D-044). One row per category makes the decision granular — dose of medicine on
    WhatsApp, booking on e-mail, diet on neither — and lets the defaults stay conservative
    while the person opts in to more.

    A missing row is not "off": it means "never touched", and the code falls back to the
    defaults in ``lembretes.notifications``. Only an explicit row overrides them, so adding a
    category later does not silently mute it for whoever already saved preferences.
    """

    category = models.CharField('categoria', max_length=10, choices=Reminder.Category.choices)
    by_email = models.BooleanField('por e-mail', default=False)
    by_whatsapp = models.BooleanField('por whatsapp', default=False)

    class Meta:
        verbose_name = 'preferência de canal'
        verbose_name_plural = 'preferências de canal'
        ordering = ['category']
        constraints = [
            models.UniqueConstraint(fields=['user', 'category'], name='uma_preferencia_por_categoria'),
        ]

    def __str__(self):
        canais = [nome for ligado, nome in ((self.by_email, 'e-mail'), (self.by_whatsapp, 'WhatsApp')) if ligado]
        return f'{self.get_category_display()}: {" e ".join(canais) or "silenciado"}'
