# Generated by Django 6.0.8 on 2026-08-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='target_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Linha de meta no gráfico de evolução de peso. Em branco, o gráfico mostra só o real.', max_digits=5, null=True, verbose_name='peso-alvo (kg)'),
        ),
    ]
