# Generated by Django 6.0.8 on 2026-08-31 19:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'grupo muscular',
                'verbose_name_plural': 'grupos musculares',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=140, verbose_name='nome')),
                ('type', models.CharField(choices=[('strength', 'Força'), ('cardio', 'Cardio'), ('mobility', 'Mobilidade'), ('functional', 'Funcional')], default='strength', max_length=12, verbose_name='tipo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='treino.musclegroup', verbose_name='grupo muscular')),
            ],
            options={
                'verbose_name': 'exercício',
                'verbose_name_plural': 'exercícios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoutineDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('label', models.CharField(help_text='Ex.: A, B, Push, Pull, Legs.', max_length=60, verbose_name='rótulo')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ordem')),
                ('muscle_groups', models.ManyToManyField(blank=True, related_name='routine_days', to='treino.musclegroup', verbose_name='grupos musculares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'divisão da ficha',
                'verbose_name_plural': 'divisões da ficha',
                'ordering': ['routine', 'order'],
            },
        ),
        migrations.CreateModel(
            name='RoutineExerciseTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('target_sets', models.PositiveSmallIntegerField(default=3, verbose_name='séries alvo')),
                ('target_reps', models.CharField(default='10', help_text='Ex.: 10, 8-12, até a falha.', max_length=20, verbose_name='repetições alvo')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ordem')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_targets', to='treino.exercise', verbose_name='exercício')),
                ('routine_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_targets', to='treino.routineday', verbose_name='divisão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'exercício da divisão',
                'verbose_name_plural': 'exercícios da divisão',
                'ordering': ['routine_day', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SessionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('rest_seconds', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='descanso (s)')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='observação')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ordem')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='treino.exercise', verbose_name='exercício')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'exercício da sessão',
                'verbose_name_plural': 'exercícios da sessão',
                'ordering': ['session', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('set_number', models.PositiveSmallIntegerField(verbose_name='série nº')),
                ('reps', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='repetições')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='carga (kg)')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='treino.sessionentry', verbose_name='exercício')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'série',
                'verbose_name_plural': 'séries',
                'ordering': ['entry', 'set_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=140, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'ficha',
                'verbose_name_plural': 'fichas',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.AddField(
            model_name='routineday',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='treino.workoutroutine', verbose_name='ficha'),
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='data')),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='duração (min)')),
                ('notes', models.TextField(blank=True, verbose_name='anotações')),
                ('routine_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='treino.routineday', verbose_name='divisão seguida')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'sessão de treino',
                'verbose_name_plural': 'sessões de treino',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='sessionentry',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='treino.workoutsession', verbose_name='sessão'),
        ),
        migrations.AddConstraint(
            model_name='musclegroup',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='grupo_unico_por_usuario'),
        ),
        migrations.AddConstraint(
            model_name='routineexercisetarget',
            constraint=models.UniqueConstraint(fields=('routine_day', 'exercise'), name='exercicio_unico_por_divisao'),
        ),
        migrations.AddConstraint(
            model_name='setlog',
            constraint=models.UniqueConstraint(fields=('entry', 'set_number'), name='numero_unico_por_entrada'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', '-date'], name='treino_work_user_id_82fae4_idx'),
        ),
    ]
