# Generated by Django 6.0.8 on 2026-09-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineexercisetarget',
            name='rest_seconds',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ex.: 90. Arma o cronômetro da tela de registro.', null=True, verbose_name='descanso (s)'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='morning_after',
            field=models.CharField(blank=True, choices=[('ok', 'Igual ou melhor'), ('worse', 'Pior que o normal')], help_text='Como o corpo amanheceu no dia seguinte a este treino.', max_length=8, verbose_name='manhã seguinte'),
        ),
    ]
