# Generated by Django 6.0.8 on 2026-09-15 16:58

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, help_text='PDF, JPG ou PNG, até 10 MB.', null=True, upload_to=core.validators.chat_attachment_upload_path, validators=[core.validators.validate_attachment], verbose_name='anexo'),
        ),
    ]
