# Generated by Django 6.0.8 on 2026-08-31 18:44

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('specialty', models.CharField(blank=True, max_length=120, verbose_name='especialidade')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('clinic_name', models.CharField(blank=True, max_length=180, verbose_name='clínica')),
                ('clinic_address', models.CharField(blank=True, max_length=255, verbose_name='endereço da clínica')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'médico',
                'verbose_name_plural': 'médicos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('start_date', models.DateField(verbose_name='início')),
                ('end_date', models.DateField(blank=True, help_text='Em branco enquanto continuar.', null=True, verbose_name='término')),
                ('status', models.CharField(choices=[('ongoing', 'Em andamento'), ('finished', 'Concluído'), ('paused', 'Pausado'), ('cancelled', 'Cancelado')], default='ongoing', max_length=10, verbose_name='situação')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='saude.doctor', verbose_name='médico responsável')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'tratamento',
                'verbose_name_plural': 'tratamentos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('dosage', models.CharField(blank=True, help_text='Ex.: 1 comprimido, 50 mg.', max_length=80, verbose_name='dose')),
                ('frequency', models.CharField(blank=True, help_text='Como está na receita. Ex.: 8/8h, 1x ao dia.', max_length=80, verbose_name='frequência')),
                ('start_date', models.DateField(verbose_name='início')),
                ('end_date', models.DateField(blank=True, help_text='Em branco para uso contínuo.', null=True, verbose_name='término')),
                ('schedule_times', models.JSONField(blank=True, default=list, help_text='Horários do dia, separados por vírgula. Ex.: 08:00, 20:00.', verbose_name='horários')),
                ('is_active', models.BooleanField(default=True, verbose_name='em uso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='saude.treatment', verbose_name='tratamento')),
            ],
            options={
                'verbose_name': 'medicamento',
                'verbose_name_plural': 'medicamentos',
                'ordering': ['-is_active', 'name'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='saude_medic_user_id_6d6bb6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=180, verbose_name='nome do exame')),
                ('requested_date', models.DateField(verbose_name='solicitado em')),
                ('scheduled_date', models.DateField(blank=True, help_text='Data marcada para a coleta ou o procedimento.', null=True, verbose_name='agendado para')),
                ('done_date', models.DateField(blank=True, null=True, verbose_name='realizado em')),
                ('result_summary', models.TextField(blank=True, help_text='O que está escrito no laudo. Transcrição, não interpretação.', verbose_name='resumo do resultado')),
                ('attachment', models.FileField(blank=True, help_text='PDF, JPG ou PNG, até 10 MB.', null=True, upload_to=core.validators.attachment_upload_path, validators=[core.validators.validate_attachment], verbose_name='laudo')),
                ('status', models.CharField(choices=[('requested', 'Solicitado'), ('scheduled', 'Agendado'), ('done', 'Realizado')], default='requested', max_length=10, verbose_name='situação')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='saude.doctor', verbose_name='solicitante')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='saude.treatment', verbose_name='tratamento')),
            ],
            options={
                'verbose_name': 'exame',
                'verbose_name_plural': 'exames',
                'ordering': ['-requested_date'],
                'indexes': [models.Index(fields=['user', '-requested_date'], name='saude_exam_user_id_0c6ef0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('date', models.DateField(verbose_name='data')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='motivo')),
                ('notes', models.TextField(blank=True, verbose_name='anotações da consulta')),
                ('next_return_date', models.DateField(blank=True, help_text='Quando o médico pediu para voltar. Vira lembrete.', null=True, verbose_name='retorno em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='saude.doctor', verbose_name='médico')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='saude.treatment', verbose_name='tratamento')),
            ],
            options={
                'verbose_name': 'consulta',
                'verbose_name_plural': 'consultas',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='saude_appoi_user_id_090a4d_idx')],
            },
        ),
    ]
