# Generated by Django 6.0.8 on 2026-09-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='next_return_date',
            field=models.DateField(blank=True, help_text='Quando o médico pediu para voltar. Vira dois lembretes: um 15 dias antes, para você marcar a consulta, e outro no dia.', null=True, verbose_name='retorno em'),
        ),
    ]
