# Generated by Django 6.0.8 on 2026-09-02 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0002_alter_appointment_next_return_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user', 'next_return_date'], name='saude_appoi_user_id_c5c356_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['user', 'scheduled_date'], name='saude_exam_user_id_11e501_idx'),
        ),
    ]
