# Generated by Django 6.0.8 on 2026-09-02 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0003_appointment_saude_appoi_user_id_c5c356_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(help_text='Ex.: hemograma completo.', max_length=140, verbose_name='título')),
                ('sample_kind', models.CharField(choices=[('edta', 'Tubo EDTA'), ('fluoreto', 'Fluoreto'), ('soro', 'Soro'), ('urina', 'Urina'), ('outro', 'Outro')], default='soro', max_length=10, verbose_name='material')),
                ('sample_label', models.CharField(blank=True, help_text='O selo que aparece no cartão. Em branco, usa o nome do material.', max_length=40, verbose_name='etiqueta do material')),
                ('method', models.CharField(blank=True, help_text='Como está no laudo. Ex.: sangue total com EDTA · citometria de fluxo.', max_length=180, verbose_name='material e método')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ordem')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_panels', to='saude.exam', verbose_name='exame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'painel laboratorial',
                'verbose_name_plural': 'painéis laboratoriais',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=140, verbose_name='exame')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='unidade')),
                ('value', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='resultado')),
                ('previous_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='resultado anterior')),
                ('previous_label', models.CharField(blank=True, help_text='Ex.: dez/25.', max_length=40, verbose_name='quando foi o anterior')),
                ('scale_min', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='início da régua')),
                ('scale_max', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='fim da régua')),
                ('ref_low', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='referência mínima')),
                ('ref_high', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='referência máxima')),
                ('status', models.CharField(choices=[('ok', 'Na meta'), ('watch', 'Atenção'), ('out', 'Fora da meta')], default='ok', max_length=6, verbose_name='situação')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='observação')),
                ('decimals', models.PositiveSmallIntegerField(default=1, verbose_name='casas decimais')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ordem')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='saude.labpanel', verbose_name='painel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'resultado laboratorial',
                'verbose_name_plural': 'resultados laboratoriais',
                'ordering': ['panel', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('kind', models.CharField(choices=[('alert', 'Ponto de atenção'), ('alignment', 'Alinhar com o médico')], default='alert', max_length=10, verbose_name='tipo')),
                ('severity', models.CharField(choices=[('critical', 'Crítico'), ('warning', 'Atenção'), ('positive', 'Evolução boa'), ('info', 'Informativo')], default='info', max_length=10, verbose_name='gravidade')),
                ('title', models.CharField(max_length=140, verbose_name='título')),
                ('body', models.TextField(verbose_name='texto')),
                ('icon', models.CharField(blank=True, help_text='Nome do ícone Lucide. Ex.: shield-alert.', max_length=40, verbose_name='ícone')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ordem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'nota clínica',
                'verbose_name_plural': 'notas clínicas',
                'ordering': ['kind', 'order', 'id'],
                'indexes': [models.Index(fields=['user', 'kind', 'order'], name='saude_clini_user_id_76aa5f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='labpanel',
            index=models.Index(fields=['user', 'order'], name='saude_labpa_user_id_204166_idx'),
        ),
    ]
