# Generated by Django 6.0.8 on 2026-09-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0004_labpanel_labresult_clinicalnote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='cycle_alternates_after',
            field=models.BooleanField(default=False, help_text='Terminada a fase diária, passa a tomar em dias alternados.', verbose_name='alterna dias depois'),
        ),
        migrations.AddField(
            model_name='medication',
            name='cycle_daily_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Só para esquema em fases. Ex.: 30 dias todo dia e depois dias alternados.', null=True, verbose_name='dias da fase diária'),
        ),
    ]
