# Generated by Django 6.0.8 on 2026-09-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0005_medication_cycle_alternates_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='weekdays',
            field=models.JSONField(blank=True, default=list, help_text='Em branco, todo dia. Marque os dias para remédio semanal.', verbose_name='dias da semana'),
        ),
    ]
