# Generated by Django 6.0.8 on 2026-08-31 19:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=140, verbose_name='nome')),
                ('goal', models.CharField(choices=[('weight_loss', 'Emagrecimento'), ('maintenance', 'Manutenção'), ('weight_gain', 'Ganho de massa')], default='maintenance', max_length=12, verbose_name='objetivo')),
                ('daily_calorie_target', models.PositiveIntegerField(blank=True, null=True, verbose_name='meta de calorias (kcal)')),
                ('protein_target_g', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='meta de proteína (g)')),
                ('carbs_target_g', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='meta de carboidrato (g)')),
                ('fat_target_g', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='meta de gordura (g)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'dieta',
                'verbose_name_plural': 'dietas',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=140, verbose_name='nome')),
                ('portion_base_g', models.PositiveSmallIntegerField(default=100, verbose_name='porção base (g)')),
                ('calories', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='calorias (kcal)')),
                ('protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='proteína (g)')),
                ('carbs_g', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='carboidrato (g)')),
                ('fat_g', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='gordura (g)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'alimento',
                'verbose_name_plural': 'alimentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='data')),
                ('meal_name', models.CharField(help_text='Ex.: café da manhã, almoço, lanche.', max_length=80, verbose_name='refeição')),
                ('quantity_g', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='quantidade (g)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='nutricao.food', verbose_name='alimento')),
            ],
            options={
                'verbose_name': 'registro diário',
                'verbose_name_plural': 'registros diários',
                'ordering': ['-date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(help_text='Ex.: café da manhã, almoço, lanche.', max_length=80, verbose_name='nome')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='horário sugerido')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ordem')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutricao.diet', verbose_name='dieta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'refeição',
                'verbose_name_plural': 'refeições',
                'ordering': ['diet', 'order', 'time'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('quantity_g', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='quantidade (g)')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_items', to='nutricao.food', verbose_name='alimento')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutricao.meal', verbose_name='refeição')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'item da refeição',
                'verbose_name_plural': 'itens da refeição',
                'ordering': ['meal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='data')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='peso (kg)')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='observação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'registro de peso',
                'verbose_name_plural': 'registros de peso',
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='alimento_unico_por_usuario'),
        ),
        migrations.AddIndex(
            model_name='dailylog',
            index=models.Index(fields=['user', '-date'], name='nutricao_da_user_id_290f47_idx'),
        ),
        migrations.AddConstraint(
            model_name='weightlog',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='um_peso_por_dia'),
        ),
    ]
