# Generated by Django 6.0.8 on 2026-09-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='change_note',
            field=models.CharField(blank=True, help_text='O que essa refeição ganhou em relação ao plano anterior. Aparece no comparador.', max_length=180, verbose_name='o que mudou'),
        ),
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.CharField(blank=True, help_text='Como a refeição é montada, em uma linha. Ex.: 25 g de tapioca · 3 ovos.', max_length=240, verbose_name='descrição'),
        ),
    ]
