# Generated by Django 6.0.8 on 2026-09-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricao', '0002_meal_change_note_meal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='recipe',
            field=models.TextField(blank=True, help_text='A receita, quando o alimento é preparado em casa. Aparece na tela do alimento.', verbose_name='preparo'),
        ),
        migrations.AddField(
            model_name='food',
            name='unit_label',
            field=models.CharField(blank=True, help_text='No singular. Ex.: ovo, fatia, unidade.', max_length=20, verbose_name='nome da unidade'),
        ),
        migrations.AddField(
            model_name='food',
            name='unit_weight_g',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Preencha para o alimento que se conta, não se pesa. Ex.: 50 para um ovo.', max_digits=6, null=True, verbose_name='peso de uma unidade (g)'),
        ),
    ]
