# Generated by Django 6.0.8 on 2026-08-31 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('category', models.CharField(choices=[('remedio', 'Remédio'), ('exame', 'Exame'), ('retorno', 'Retorno médico'), ('treino', 'Treino'), ('nutricao', 'Nutrição'), ('outro', 'Outro')], max_length=10, verbose_name='categoria')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('remind_at', models.DateTimeField(verbose_name='lembrar em')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='recorrente')),
                ('recurrence_rule', models.CharField(blank=True, help_text='Texto livre para a pessoa lembrar o padrão. Ex.: "todo dia às 08:00".', max_length=80, verbose_name='recorrência')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=10, verbose_name='situação')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado em')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='id de origem')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='tipo de origem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'lembrete',
                'verbose_name_plural': 'lembretes',
                'ordering': ['remind_at'],
                'indexes': [models.Index(fields=['user', 'status', 'remind_at'], name='lembretes_r_user_id_045b5b_idx'), models.Index(fields=['content_type', 'object_id'], name='lembretes_r_content_0f280d_idx')],
            },
        ),
    ]
