# Generated by Django 6.0.8 on 2026-09-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lembretes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='category',
            field=models.CharField(choices=[('remedio', 'Remédio'), ('exame', 'Exame'), ('retorno', 'Retorno médico'), ('agendar', 'Agendamento'), ('treino', 'Treino'), ('nutricao', 'Nutrição'), ('outro', 'Outro')], max_length=10, verbose_name='categoria'),
        ),
    ]
