# Generated by Django 6.0.8 on 2026-09-02 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lembretes', '0002_alter_reminder_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('category', models.CharField(choices=[('remedio', 'Remédio'), ('exame', 'Exame'), ('retorno', 'Retorno médico'), ('agendar', 'Agendamento'), ('treino', 'Treino'), ('nutricao', 'Nutrição'), ('outro', 'Outro')], max_length=10, verbose_name='categoria')),
                ('by_email', models.BooleanField(default=False, verbose_name='por e-mail')),
                ('by_whatsapp', models.BooleanField(default=False, verbose_name='por whatsapp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'preferência de canal',
                'verbose_name_plural': 'preferências de canal',
                'ordering': ['category'],
                'constraints': [models.UniqueConstraint(fields=('user', 'category'), name='uma_preferencia_por_categoria')],
            },
        ),
    ]
