# Generated by Django 6.0.8 on 2026-09-02 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lembretes', '0003_channelpreference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['remind_at'], 'permissions': [('manage_whatsapp', 'Pode conectar a sessão do WhatsApp')], 'verbose_name': 'lembrete', 'verbose_name_plural': 'lembretes'},
        ),
    ]
